#pragma once
#include <GLFW/glfw3.h>
#include <dawn/dawn_proc.h>
#include <dawn/webgpu_cpp.h>
#include <webgpu/webgpu.h>
#include <webgpu/webgpu_glfw.h>
#include <dawn/native/DawnNative.h>
#include <dawn/utils/ComboRenderPipelineDescriptor.h>
#include <dawn/utils/WGPUHelpers.h>
#include <dawn/common/Log.h>
#include <dawn/common/Platform.h>
#include <dawn/common/SystemUtils.h>
